config/routes.rb
Starterapp::Application.routes.draw do

  get "bubble_cloud/view1"
  get "bubble_cloud/view2"
  get "bubble_cloud/view3"
  get "bubble_cloud/view4"
  resources :users
  root 'pages#home'
  get 'tweets/:type' => 'pages#home'
  get 'tweets/user/:other' => 'pages#other'
  get 'auth/:provider' => 'sessions#new', :as => :signin
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
end

app/views/shared/_footer.html.haml
%footer.text-center

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "The Logic of the Twitterverse", '#', class: 'brand'
      %ul.nav         
        %li.dropdown 
          
          %a.dropdown-toggle{:data => {:toggle => "dropdown"}, :href => "#"}
            Tweet Logic
            %b.caret
          %ul.dropdown-menu
            %li{:data => {:no_turbolink => 'true'}}= link_to "Top", root_url
            %li{:data => {:no_turbolink => 'true'}}= link_to "New", '/tweets/new'
            %li{:data => {:no_turbolink => 'true'}}= link_to "My Tweets", '/tweets/me'
            %li{:data => {:no_turbolink => 'true'}}= link_to "Users Tweets", '/tweets/user/SchoolsMemories'
        %li.dropdown 

          %a.dropdown-toggle{:data => {:toggle => "dropdown"}, :href => "#"}
            Bubble Cloud
            %b.caret
          %ul.dropdown-menu
            %li{:data => {:no_turbolink => 'true'}}= link_to "#leTour", bubble_cloud_view1_path
            %li{:data => {:no_turbolink => 'true'}}= link_to "TBC", bubble_cloud_view2_path
            %li{:data => {:no_turbolink => 'true'}}= link_to "TBC", bubble_cloud_view3_path
            %li{:data => {:no_turbolink => 'true'}}= link_to "TBC", bubble_cloud_view4_path
      %ul.nav.pull-right         
        - if user_signed_in?
          %li= link_to current_user.name, users_path(current_user) 
          %li{:data => {:no_turbolink => 'true'}}= link_to "Sign out", signout_path
        - else
          %li= link_to "Sign in with Twitter", signin_path(:twitter)